apiVersion: apps/v1
kind: Deployment
metadata:
  name: moonpie-postgres
spec:
  replicas: 2
  selector:
    matchLabels:
      app: moonpie-postgres
  template:
    metadata:
      labels:
        app: moonpie-postgres
    spec:
      containers:
        - image: postgres
          name: postgres
          env:
            - name: POSTGRES_DB
              value: postgres
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: moonpie-postgres-secrets
                  key: root_password
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          ports:
            - containerPort: 5432
              name: postgres
          volumeMounts:
            - name: moonpie-postgres-volume
              mountPath: /var/lib/postgresql/data
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
      volumes:
        - name: moonpie-postgres-volume
          persistentVolumeClaim:
            claimName: moonpie-postgres-pvc